version: '2.2'
services:
  shell:
    build: .
    restart: unless-stopped
    ports:
      - 1337:1337
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
